# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mani_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mani_arm_controller:
  ros__parameters:
    joints:
      - Revolute_1
      - Revolute_2
      - Revolute_3
      - Revolute_4
      - Revolute_5
      - Revolute_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity